
% only 1 study per RAM
pop_editoptions( 'option_storedisk', 1);

% creates STUDY
[STUDY ALLEEG] = std_editset( STUDY, ALLEEG, 'name','Control_subjects','commands',{...
    {'index' 1 'subject' '1' 'condition' 'cntrl'} ...
    {'index' 2 'subject' '2' 'condition' 'cntrl'} ...
    {'index' 3 'subject' '3' 'condition' 'cntrl'} ...
    {'index' 4 'subject' '4' 'condition' 'cntrl'} ...
    {'index' 5 'subject' '5' 'condition' 'cntrl'} ...
    {'index' 6 'subject' '6' 'condition' 'cntrl'} ...
    {'index' 7 'subject' '7' 'condition' 'cntrl'} ...
    {'index' 8 'subject' '8' 'condition' 'cntrl'} ...
    {'index' 9 'subject' '9' 'condition' 'cntrl'} ...
    {'index' 10 'subject' '10' 'condition' 'cntrl'} ...
    {'index' 11 'subject' '11' 'condition' 'cntrl'} ...
    {'index' 12 'subject' '12' 'condition' 'cntrl'} ...
    },'updatedat','on','savedat','on','rmclust','on' );

[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
% EEG = eeg_checkset( EEG );

eeglab redraw

