% load sets

p = cd; % getting current directory

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename',{...
    'RS_EC_S1.set' ...
    'RS_EC_S2.set' ...
    'RS_EC_S3.set' ...
    'RS_EC_S4.set' ...
    'RS_EC_S5.set' ...
    'RS_EC_S6.set' ...
    'RS_EC_S7.set' ...
    'RS_EC_S8.set' ...
    'RS_EC_S9.set' ...
    'RS_EC_S10.set' ...
    'RS_EC_S11.set' ...
    'RS_EC_S12.set'}, ...
    'filepath',p);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 0,'study',0); 
eeglab redraw